## Numpy

- Numpy or numerical python is a built in library in python that allows analysts to manipulate data easily.
- Numpy arrays are extremely useful for data analysts to use to aggregate their data.
- The dimensions of numpy arrays can also be changed so data analysts can do matrix functions using numpy.

In [1]:
#Import Statement
import numpy as np

# Numpy Arrays

- A numpy array can be created from a list or tuple.
- They act similar to a list

In [4]:
#1D array
array_1d = np.array([1, 2, 3, 4])
print(array_1d)

print('-'*15)
#2D array must be passed in as a list of lists or tuples
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

[1 2 3 4]
---------------
[[1 2 3]
 [4 5 6]]


# Arrays Using Built In Functions

In [6]:
# Array of zeros rows, columns
zeros_array = np.zeros((2,3)) # 000
                              # 000
print(zeros_array)

print('-'*20)

#Array of ones rows, columns
ones_array = np.ones((3,2)) # 11
                            # 11
                            # 11
print(ones_array)

print('-'*20)

#Array from a range
range_array = np.arange(0, 10, 2) #Start at 0 go to 10 by 2s
print(range_array)

print('-'*20)

#Array of evenly spaced numbers
linspace_array = np.linspace(0, 1, 5) #Space each entry from 0 to 1 evenly and use 5 entries
print(linspace_array)

[[0. 0. 0.]
 [0. 0. 0.]]
--------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]]
--------------------
[0 2 4 6 8]
--------------------
[0.   0.25 0.5  0.75 1.  ]


## Array Properties

In [8]:
print(f'Shape {array_2d.shape}') #Dimensions of the array
print(f'Size {array_2d.size}') #Total amount of elements in the array
print(f'Data type {array_2d.dtype}') #The datatype of the elements in the array


Shape (2, 3)
Size 6
Data type int32


## Array Operations

Basic Arithmetic: each entry in the first array is lined up with the corresponding entry in the second array

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b) #Addition
print(a - b) #Subtraction
print(a * b) #Multiplication
print(a / b) #Division

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Statistical Functions

In [10]:
data = np.array([1, 2, 3, 4, 5])

print(f'Mean {np.mean(data)}')
print(f'Median {np.median(data)}')
print(f'Standard Deviation {np.std(data)}')
print(f'Variance {np.var(data)}')

Mean 3.0
Median 3.0
Standard Deviation 1.4142135623730951
Variance 2.0


Reshaping Arrays

In [19]:
original = np.arange(12)
print(original)

print('-' * 50)

reshaped_array = np.arange(12).reshape(3,4) #Reshape a 1 row 12 column array to a 3 row 4 column array
print(reshaped_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
--------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Indexing and Slicing

In [12]:
#Indexing
print(array_2d)

print('-' * 20)

print(array_2d[0, 1]) #Access element at row 0 column 1

#Slicing
print(array_2d[0, :]) #First row
print(array_2d[:, 1]) #Second column

[[1 2 3]
 [4 5 6]]
--------------------
2
[1 2 3]
[2 5]


In [14]:
#argmax- returns the index of the largest element
print(array_1d)

print('-' * 20)

print(np.argmax(array_1d))

#argmin- returns the index of the smallest element
print(np.argmin(array_1d))

[1 2 3 4]
--------------------
3
0


Combining Arrays

In [21]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

#Vertically Stack the arrays
vstacked_array = np.vstack((array_1, array_2))
print(vstacked_array)

print('-' * 20)

#Horizontally Stack the arrays
hstacked_array = np.hstack((array_1, array_2))
print(hstacked_array)

print('-' * 20)

#Concatenate the arrays
concat_array = np.concatenate((array_1, array_2))
print(concat_array)

[[1 2 3]
 [4 5 6]]
--------------------
[1 2 3 4 5 6]
--------------------
[1 2 3 4 5 6]


Many of these functions can also be used on columns and rows in a dataframe. This is why numpy is so useful in data analytics projects. There are many more numpy functions to explore on the numpy documentation.

Source: ChatGPT